#!/bin/bash

NAME=${PWD##*docker-}
IMAGE_NAME=yokogawa/${NAME}
docker rm ${NAME}

set -x
if [ "${1}" = "bash" ]; then
    docker run -v ${PWD}/spec/:/opt/app/spec/ -i -t --entrypoint="/bin/bash" --name=${NAME} ${IMAGE_NAME}
else
    docker run -t -v ${PWD}/spec/:/opt/app/spec/ --name=${NAME} ${IMAGE_NAME} $@
fi
